@WorldLeague.Api_HostAddress = http://localhost:5206

POST {{WorldLeague.Api_HostAddress}}/api/draws
Accept: application/json
Content-Type: application/json

{
  "drawerName" : "Http",
  "drawerLastName" : "File",
  "numberOfGroups" : 4
}

###
POST {{WorldLeague.Api_HostAddress}}/api/draws
Accept: application/json
Content-Type: application/json

{
  "drawerName" : "Http",
  "drawerLastName" : "File",
  "numberOfGroups" : 8
}

###
